### ISSUE TITLE
Works this with VDR

### ISSUE THREAD

**Issue by joeduck** [ferranti-dvb/satip-client#1]
Hi,

works your Software also with VDR? Got on compile on Debian Wheezy this Error:

satip_vtuner.c: In function ‘get_property’:
satip_vtuner.c:714:5: error: duplicate case value
satip_vtuner.c:688:5: error: previously used here
make: *** [satip_vtuner.o] Fehler 1

**Comment by chrwick** [comment]
Hi,

yes, it should. You have found a bug, which I have not came across because you are using an old DVB API version. I only develop using DVB API version 5.10. So I would recommend that you use the latest DVB API version.

**Comment by chrwick** [comment]
However, line 714 is wrong.
It should be DTV_DVBT2_PLP_ID and not DTV_PILOT.

It should fix the compilation. The code however is not used anyway at runtime (DTV_GET_PROPERTY API CALL).

**Comment by ferranti-dvb** [comment]
Hi,

yes, it should. You have found a bug, which I have not came across because you are using an old DVB API version. I only develop using DVB API version 5.10. So I would recommend that you use the latest DVB API version.

**Comment by ferranti-dvb** [comment]
However, line 714 is wrong.
It should be DTV_DVBT2_PLP_ID and not DTV_PILOT.

It should fix the compilation. The code however is not used anyway at runtime (DTV_GET_PROPERTY API CALL).

**Comment by ferranti-dvb** [comment]
Fixed.
